package com.example.diseomac.treino.Model;

import io.realm.RealmObject;

/**
 * Created by diseomac on 11/09/17.
 */

public class Treino extends RealmObject {

    private String name;
    private String description;

    private int id;

    // Standard getters & setters generated by your IDE…
    public String getName() { return name; }
    public void   setName(String name) { this.name = name; }
    public String getDescr() { return description; }
    public void   setDescr(String description) { this.description = description; }

    public int    getId() { return id; }
    public void   setId(int id) { this.id = id; }
}
